open! Ppxlib
open! Stdppx

(** [boxed_witness core_type] produces an expression for the boxed witness associated with
    [core_type].

    This references the [boxed] witness generated by [[@@deriving box]] for named types,
    according to the usual naming convention. *)
val boxed_witness : core_type -> expression

(**/**)

module Private : sig
  (** These modules are only intended for use by [ppx_box] itself. *)

  module Common = Common
  module Expander = Expander
  module Record = Record
  module Tuple = Tuple
end
